langchain4j:
  community:
    dashscope:
      tokenizer:
        api-key: sk-da3ae08b2a9741d687ccb37a8d8c1029
        model-name: qwen-plus
      # LLM
      chat-model:
        api-key: sk-da3ae08b2a9741d687ccb37a8d8c1029
        model-name: qwen-plus
        temperature: 0.7
      # Streaming LLM
      streaming-chat-model:
        api-key: sk-da3ae08b2a9741d687ccb37a8d8c1029
        model-name: qwen-plus
        temperature: 0.7
      # Embedding model
      embedding-model:
        api-key: sk-da3ae08b2a9741d687ccb37a8d8c1029
        model-name: text-embedding-v3
        dimensions: 1024


# Embedding model - PgVector
pgvector:
  database: vecdb
  host: ${SERVER_IP}
  port: 5432
  user: postgres
  password: postgres
  table: vectors_db

# search engine
search:
  engine: google
  api-key: ${SEARCH_ENGINE_API}

# personal LLM
llm:
  apikey: ${DEEPSEEK_API_KEY}
  model: deepseek-reasoner
  baseUrl: https://api.deepseek.com
