# MinerU PDF解析器配置 - 直接使用七牛云URL
mineru:
  api:
    # MinerU API服务地址
    base-url: https://mineru.net
    
    # MinerU API Token
    token: eyJ0eXBlIjoiSldUIiwiYWxnIjoiSFM1MTIifQ.eyJqdGkiOiI1NTcwNTYzOCIsInJvbCI6IlJPTEVfUkVHSVNURVIiLCJpc3MiOiJPcGVuWExhYiIsImlhdCI6MTc1Mzk0NjU3OCwiY2xpZW50SWQiOiJsa3pkeDU3bnZ5MjJqa3BxOXgydyIsInBob25lIjoiIiwib3BlbklkIjpudWxsLCJ1dWlkIjoiMmRkMGM1NzQtNGE0NS00MTFiLTk4MGMtNDk2YjM4ZGU5YTQ4IiwiZW1haWwiOiIiLCJleHAiOjE3NTUxNTYxNzh9._hE0eRpgD0S02YF-T_0mAK9gODUcafFA1PtrbBjYPZZofcBAXpKx-qqAGmkLMMS8QzvFr8nPT1gKDc7xWjDh-A
    
    # 是否启用MinerU解析器
    enabled: true
    
    # 解析超时时间（秒）
    timeout: 300
    
    # 轮询间隔（秒）
    poll-interval: 5
    
    # 是否启用OCR功能
    is-ocr: true
    
    # 是否启用公式识别
    enable-formula: true
    
    # 是否启用表格识别
    enable-table: true
    
    # 文档语言设置
    language: auto
    
    # 模型版本
    model-version: v2
